[webserver]
may1 ansible_host=10.0.2.100 ansible_port=22

[dbserver]
may2 ansible_host=10.0.2.101 ansible_port=22

[gitlab_server]
may1 ansible_host=10.0.2.100 ansible_port=22

[all_servers:children]
webserver
dbserver
gitlab_server

[all_servers:vars]
ansible_user=daoson
ansible_ssh_private_key_file=~/.ssh/ansible_key
ansible_become=yes
ansible_become_method=sudo
