---
- name: Cài MySQL Server
  dnf:
    name:
      - mysql-server
      - python3-PyMySQL
    state: present

- name: Start và enable MySQL
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Tạo database
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  loop: "{{ mysql_databases }}"

- name: Tạo user MySQL
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  loop: "{{ mysql_users }}"
